### ISSUE TITLE
update bootstrap, css

### ISSUE THREAD

**Issue by matthewlee626** [titanhacks/hackathon#2]
website has been looking subpar. needs to be changed for QOL

**Comment by rspineda** [comment]
i just sent a pull request with Improvements of the webpage design , separation of assets in different folder and improved behavior with elements.
I left the index file you had with a new name (index(former).html ) so you can compare the changes and the content with the new file (index.html)
I took care of the structure and content you had, so You will find exactly the same information but with a different style and behavior.
I hope you like it.

Greetings from Madrid.
